language: node_js

node_js:
  - lts/*

install:
  - yarn install
  - cd functions
  - yarn install
  - cd ..

script:
  - yarn build

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_CI_TOKEN
